### ISSUE TITLE
[Featurerequest] Valhalla support

### ISSUE THREAD

**Issue by Draakoor** [ark-mod/ArkBot#123]
Hello,

can you please add support for valhalla?
https://ark.gamepedia.com/Mod:Valhalla_Map/Resource_Map
https://steamcommunity.com/sharedfiles/filedetails/?id=504122600

Thanks

**Comment by SirShaw** [comment]
@Draakoor please check our discord for up to date development talk.  We are working on adding addtional maps currently. Thank You.
