### ISSUE TITLE
Giving custom WebAPI URL for frontend

### ISSUE THREAD

**Issue by Getty** [ark-mod/ArkBot#131]
Great product, first to say, all pretty much perfect. One little details: I am running an environment with traefik, which handles normally the SSL topic directly at the front, which is no problem for the Web App itself, as I can tell him its https://myserver/ and just redirect to port 80 and it works out. But I can't give a custom URL for the API, like it would be trivial for me to redirect https://api.myserver/ to http://ip-server:60001/ but only because of the frontend webpages not allowing me to "set" the URL, this doesn't work. But even if I just want it to be on https://myserver:60001/ I still can't do that without activating the SSL and then I have to handle port 80 again directly so that the Letsencrypt come.... yeah it goes dizzy! :D So yeah just a Web API URL parameter that allows override of what is used in the webfrontend would be awesome! Thanks again for this epic product.

**Comment by Getty** [comment]
I actually just realized that I can indeed just try to make it https:// with traefik and pass through to the listener i just need to make it at least through the port. So that case can actually work.

**Comment by mxtsdev** [comment]
I'm not familiar with traefik but it sounds like you are trying to redirect incoming https requests to http endpoints for both the web app and the web api.

Making a forwarding rule based on the incoming port should be possible in traefik
https://docs.traefik.io/routing/routers/
`--entryPoints.webapi.address=:60001`

Is there another issue here with the steam auth?

**Comment by Getty** [comment]
There is a lot of issue in this. You just can't make him clear that the Web API points are https although he offeres them as http, and the steam URL with http is a general problem of the Steam library you are using in the software, so that fixing will be anyway harder.

I am not really thinking that after the chat in your Discord and after the reply you are giving here, that anyone of your crew ever care about actually understanding the situation i talk about, it should be kinda obvious what happens if you run ArkBot on http:// while you have a front proxy that converts the port to https://, i really do not want to continue explaining this.

Thanks for trying tho, or whatever.
