### ISSUE TITLE
Online Players not querying with update: ArkBot_CIBuild_master_20200226.2

### ISSUE THREAD

**Issue by doublee313** [ark-mod/ArkBot#135]
I have updated from the 1.91 to ArkBot_CIBuild_master_20200226.2 to help test.

I've noticed my Online Players is staying at 0 even know players are on. I reverted back to 1,91 and it's working again. 

I might have missed something or doing something wrong....but figured I'd pop it up :)

Thx guys.

**Comment by SirShaw** [comment]
Mine is still working since the update. Please make sure when you are updating, you are installing Arkbot to a brand new directory and not overwriting an existing install. Simply copy your config.json from the old install to the new folder and launch. Arkbot doesn’t like when files are overwrote.

**Comment by doublee313** [comment]
I overwrote the files. Thx......Will try this and report back.

**Comment by doublee313** [comment]
Tried that and it seems to just not query with the latest files...

https://snipboard.io/2VFsAq.jpg
https://snipboard.io/wCgi7W.jpg

If i revert back to the previous version it seems to work.

**Comment by doublee313** [comment]
Issued resolved with: ArkBot_CIBuild_master_20200306.1  or fixed on my end (something i had messed up). Thx.
