### ISSUE TITLE
No data could be loaded for the given steam id.

### ISSUE THREAD

**Issue by Soldize** [ark-mod/ArkBot#149]
Hi,

When I click on my profile I get the message No data could be loaded for the given steam id. This mistake was not yesterday.

I have moved my server to another hard drive. The ArkBot Config has been adjusted and shows no errors in the log.

Can you help me?

Best regards

**Comment by SirShaw** [comment]
please do not use github as a support forum as per the readme.  Join our discord if you need help.  This issue was fixed in the most recent version of ark.  Thank You.
