### ISSUE TITLE
Can´t install and open the app

### ISSUE THREAD

**Issue by IslaCalavera** [ark-mod/ArkBot#154]
hi, i try to run the program, but it doesn't respond. He spends 30 seconds thinking and then nothing. I think it is because i need some program. Because it happens to me since I reinstalled the computer.

I have tried it on another pc that I have and it installs and run perfectly.

Does anyone know what programs you need to make it work?

THX!

**Comment by SirShaw** [comment]
You need to make sure you have the dependencies installed that are listed in the README.md on the main page. Thank you.
