### ISSUE TITLE
Structure search radius configurable

### ISSUE THREAD

**Issue by wmrojer** [ark-mod/ArkBot#43]
It would be nice if it was possible to configure how far out it tries find more structures from the same tribe to add to the same circle on the Admin Structures page. 
This is specially noticeable on the Aberration map where a lot of the tribes get huge circles that all overlap each other. Several smaller circles would be preferable to make cleaning some stuff with the tool instead of wiping there tribes entire base.

**Comment by wmrojer** [comment]
[Sample Image](https://screenshots.firefox.com/kjYhyRrVURiJUZIS/app.arksverige.se)

**Comment by wmrojer** [comment]
[Sample Image](https://screenshots.firefox.com/kjYhyRrVURiJUZIS/app.arksverige.se)

**Comment by tsebring** [comment]
This should be an option in the configuration.
