### ISSUE TITLE
Crash after server update

### ISSUE THREAD

**Issue by UncleMyers** [ark-mod/ArkBot#48]
The bot crashes after startup.

**Comment by Foppa01** [comment]
can you add crash logs?

**Comment by Swat1801** [comment]
[application.log](https://github.com/tsebring/ArkBot/files/1925032/application.log)
[applicationcrash_CurrentDomain_UnhandledException_2018-04-18.19.02.37.3654.log](https://github.com/tsebring/ArkBot/files/1925033/applicationcrash_CurrentDomain_UnhandledException_2018-04-18.19.02.37.3654.log)

**Comment by SirShaw** [comment]
this appears to be a configuration issue given the error report.
