### ISSUE TITLE
Destroy Structures in this area not working.

### ISSUE THREAD

**Issue by 1david25** [ark-mod/ArkBot#58]
Is this feature not fully working? It shows as disabled by default. When I assigned it to a group it has the functionality but refuses to actually do it.

**Comment by Foppa01** [comment]
Hi @1david25 
It works, I have no problems with it on my web companion. 
But I guess you have changed this section
`    "admin-server": {
      "players": [ "admin" ],
      "tribes": [ "admin" ],
      "structures": [ "admin" ],
      "structures-rcon": [ "admin" ]
    }`

Most important part to actually make it work is that the structures-rcon is enabled for that group.

**Comment by 1david25** [comment]
I have it as you have it. I am getting the following error,
Action Failed...
Timeout while waiting for command response...

**Comment by 1david25** [comment]
Found issue. Make sure you change you       "ip": "whatever", to your multihome port!

**Comment by TOXid** [comment]
I have problem with this function. It response:
"Action Successfull!
Server received, But no response!!"

And no effect on server. (PVE)

**Comment by SirShaw** [comment]
this has been corrected with a new plugin.  link can be found on the main page of the project.
