### ISSUE TITLE
Arkbot is crashing and not rebooting after a few hours now.

### ISSUE THREAD

**Issue by 1david25** [ark-mod/ArkBot#60]
Could be because of the new update in ark. After having it open and running for more than 5 hours the bot goes offline but it continues to run the Web Interface. And event log is showing these errors. Keep in mind this was not an issue until this latest ark update that brought in the ark event.

https://pastebin.com/uqmueVEe

https://pastebin.com/Xf0E5FGi

https://pastebin.com/nNV4qFB2

https://pastebin.com/HVYvRj1S

**Comment by jefferson-1** [comment]
Grab the latest release. Should be fine now.
