### ISSUE TITLE
1.83 source download is actually 1.82

### ISSUE THREAD

**Issue by Lewimaron** [ark-mod/ArkBot#69]
We're currently trying to download the source for version 1.83 (including the steam login fix and config changes), but the linked source under that release is actually version 1.82.

Is there a complete source for 1.83 that we can download somewhere?

**Comment by flagoss** [comment]
The BETA branch is 1.83. Just make sure to select the beta branch in Visual Studio.
![image](https://user-images.githubusercontent.com/10181607/44631206-f47d9880-a936-11e8-82b7-0b4bb0810df2.png)
