### ISSUE TITLE
Problem Using on my Box

### ISSUE THREAD

**Issue by nosborbr** [ark-mod/ArkBot#76]
I have a windows Server 2012 R2. Where i have all my servers working. "Personal BOX"
All my cluster is working as i meed with all plugin setup as well.
But when i execute the Arkbot it just close.
I run it well on my game pc. But on the server i try my best. Now i need help for the communite on this

**Comment by jefferson-1** [comment]
Please join us on arkbotusers in discord. Thanks :)

**Comment by nosborbr** [comment]
Send myu the link please

**Comment by nosborbr** [comment]
> Please join us on arkbotusers in discord. Thanks :Can you send me the link please. i guess i join the wrong discord

**Comment by jefferson-1** [comment]
https://discord.gg/zDJcckF

**Comment by nosborbr** [comment]
There is not arkbotusers channel on the discord or some one have to give rank to see it

**Comment by jefferson-1** [comment]
In the welcome channels it clearly says to click a reaction and you will be dropped in the appropriate channel. 

It also says that in the readme for this project.

**Comment by doublee313** [comment]
You have. NET and run times installed?
