### ISSUE TITLE
website integration

### ISSUE THREAD

**Issue by Carmichaeldb** [ark-mod/ArkBot#78]
Good Day,

I am very new to the world of coding, with my only experience being 6 months of some introductory college courses for javascript, java, html, css, php, database management, and content management (wordpress). Is there somewhere I can get information, or help, to use this api to integrate its functions into a community website? We are looking to produce a website that players can make user accounts and gain access to player list, and ingame info for their tribes. Basically all the stuff this api does just integrated onto our own website.

**Comment by jefferson-1** [comment]
Join us on discord
