### ISSUE TITLE
Unable to startup server

### ISSUE THREAD

**Issue by QuattroViper** [ark-mod/ArkBot#81]
I can't seem to get the server to startup. Is there something I am missing?
After the configuration, do I run the ArkBot.exe ? 

I am surely missing something obvious here.

**Comment by jefferson-1** [comment]
Please join Discord.

**Comment by QuattroViper** [comment]
I was on there. But can't seem to find anybody. 
 
Can I try some fixes that you got from all the other people, that might work? 

Thank you

**Comment by jefferson-1** [comment]
Im outside today so limited availability. I or others will support as we have time.
