### ISSUE TITLE
unable to connect to web api when behind reverse proxy

### ISSUE THREAD

**Issue by nappypup** [ark-mod/ArkBot#83]
I have arkbot working when on a local network however it does not when ran through my reverse proxy.  I am receiving "Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR." I have to have arkbot run without ssl due to my isp blocking port 80. I am using cloudflare to redirect traffic to https. I have other services running fine with the reverse proxy.

![](https://cdn.discordapp.com/attachments/374662006701293569/514218512558981130/unknown.png)

**Comment by jefferson-1** [comment]
if using cloudflare, just change ports ... :80 through :443 won't work too well.

**Comment by tsebring** [comment]
Not a bug in ark bot.
