### ISSUE TITLE
Dino Base Level Calculation Different from other sites ?

### ISSUE THREAD

**Issue by JamieKG** [ark-mod/ArkBot#84]
Hi When putting the stats of a dino in dododex or other dino stat calculators they always differ from arkbot ones is this a bug ?

![image](https://user-images.githubusercontent.com/3878484/49158445-14e43700-f31a-11e8-854a-99d5e5475fc0.png)
![image](https://user-images.githubusercontent.com/3878484/49158473-2594ad00-f31a-11e8-9608-dfe62147663e.png)

**Comment by tsebring** [comment]
Not a bug. Dododex values are guesstimates, while we have real ones.
