### ISSUE TITLE
Failed to apply updates to servers in cluster <Exception>

### ISSUE THREAD

**Issue by V1irus** [ark-mod/ArkBot#85]
Getting Failed to apply updates to servers in cluster every time i try to update cluster plase help

`<Exception>
  <System.ArgumentException>
    <Current>
      <Message>Ein Element mit dem gleichen Schlüssel wurde bereits hinzugefügt.</Message>
      <ParamName>null</ParamName>
    </Current>
    <Message>Ein Element mit dem gleichen Schlüssel wurde bereits hinzugefügt.</Message>
    <TargetSite>Void ThrowArgumentException(System.ExceptionResource)</TargetSite>
    <Source>mscorlib</Source>
    <StackTrace><![CDATA[bei System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
bei System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
bei System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
bei ArkSavegameToolkitNet.Domain.ArkGameDataBase.Initialize(ArkClusterDataBase clusterData) in C:\Users\Ripper\Documents\GitHub\ArkSavegameToolkitNet\ArkSavegameToolkitNet.Domain\ArkGameDataBase.cs:Zeile 150.
bei ArkSavegameToolkitNet.Domain.ArkGameData.ApplyNewData(ArkSavegame save, ArkTamedCreature[] tamed, ArkWildCreature[] wild, ArkPlayer[] players, ArkTribe[] tribes, ArkItem[] items, ArkStructure[] structures, Boolean decouple, ArkAnonymizeData anonymize) in C:\Users\Ripper\Documents\GitHub\ArkSavegameToolkitNet\ArkSavegameToolkitNet.Domain\ArkGameData.cs:Zeile 217.
bei ArkSavegameToolkitNet.Domain.ArkGameData.ApplyPreviousUpdate(Boolean decouple) in C:\Users\Ripper\Documents\GitHub\ArkSavegameToolkitNet\ArkSavegameToolkitNet.Domain\ArkGameData.cs:Zeile 185.
bei ArkBot.Ark.ArkClusterContext.Update(Boolean manualUpdate, IConfig fullconfig, ISavegameBackupService savegameBackupService, IProgress`1 progress, CancellationToken ct)]]></StackTrace>
  </System.ArgumentException>
</Exception>`

**Comment by jefferson-1** [comment]
Please join the discord.
