### ISSUE TITLE
instantly crashes after configuration

### ISSUE THREAD

**Issue by smipertony247** [ark-mod/ArkBot#87]
After i full set this up save restart the program it crashes every-time and does not load anything if someone could reach out to help me with this id be super super grateful my discord name is snipertony247#0001

**Comment by jefferson-1** [comment]
Probably missing one or more C++ runtimes.. I'm not sure which one it is. Easier to just download them all: 
https://www.itechtics.com/microsoft-visual-c-redistributable-versions-direct-download-links/

**Comment by smipertony247** [comment]
i downloaded them all i had most already still the same issue running windows server 2012 r2

**Comment by jefferson-1** [comment]
join us on our discord ... we'll solve it there.

**Comment by smipertony247** [comment]
> join us on our discord ... we'll solve it there.

ok i need the link please

**Comment by jefferson-1** [comment]
It's right on the main page ... Support

Please do not use Github as a support forum. If you need help, join our Discord at this link: https://discord.gg/zDJcckF and one of us will try to help as we can. Be sure to click the reaction to join the proper discord channels.
