### ISSUE TITLE
ArkBot + Windows Server 2016 = No Application Start

### ISSUE THREAD

**Issue by PryMary** [ark-mod/ArkBot#90]
Hi There,

I have gone through the config and set-up the Discord bot and everything but when I actually click the application icon, nothing happens. Nothing shows in task manager it's as if the icon does nothing at all. I tried setting run as admin and still nothing.

I saw someone removed all the C++ re-dist's so I tried that and still do dice. then ark servers wouldn't start due to missing dll's so re-installed C++ redist.

Does anyone have it running on Server 2016? If so is there any pre-req's that I need to ensure it runs?

Kind regards,

V.

**Comment by doublee313** [comment]
Do you have .net turned on on server?

**Comment by PryMary** [comment]
yep, both 3.5 and 4.6.1 have been installed. It was the first thing I did when I got the server.

**Comment by doublee313** [comment]
I had this issue. Did you run as admin? Its something with that or missing
runtime or something.

**Comment by PryMary** [comment]
Yeah I even went to compatibility and set to always run as admin. What runtimes do you have on your box? I only have 1 c++ redist on the server now. Could you do me a screenshot of your add / remove programs so I can get all the redist you have any anything else I may be missing?

**Comment by doublee313** [comment]
Try the all in one VC runtime. I use the MajorGeeks one.

**Comment by PryMary** [comment]
Oh Nice one doublee313 its now starting!!! Now to work out what I need to do with: Steam Open ID Redirect URL

I have no idea how to set this bit up! Got any advise?

**Comment by doublee313** [comment]
Im doublee#0313 in discord if you need help.
