### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by PryMary** [ark-mod/ArkBot#91]
![capture](https://user-images.githubusercontent.com/7375807/52711642-37d1cf00-2f8a-11e9-9541-9825672e68f1.PNG)

I am getting this error when trying to view the web app from my work computer, but for my home computer it is working fine and i can view each server with no issues. Though at work I get that error showing in chrome. Nothing shows at all in FireFox.

What could be causing that error?

TIA,

James

**Comment by jefferson-1** [comment]
Workplaces can have funky firewalls that could cause issues. 

Have you tried a VPN at work?

**Comment by PryMary** [comment]
Aaaah yes I didn't think of that and I have not no. I have asked some others to test the address: http://www.arkbot.teambbq.co.uk - to see if they get the issue as well but so far not heard back so am not 100% sure if its the web app or my connection from here lol

**Comment by jefferson-1** [comment]
From a Hotel Wifi in Miami, it comes up with a login page.

**Comment by PryMary** [comment]
Hmmm OK then it must be works firewall then. I'm gonna run some tests via 4g as well. Thank you Jefferson for checking it is much appreciated

**Comment by doublee313** [comment]
Do you have a proxy at work?

**Comment by jefferson-1** [comment]
Not just proxy ... Some of the newer corporate firewalls (such as Cisco's) have advanced threat detection features. Unfortunately with the way that Arkbot is coded it would likely be blocked on a few grounds. It has a gaming login (Steam), and it is built on a non standard HTTP server (not IIS or Apache for instance). So for those reasons, these firewalls may set this site to high risk and block those elements while delivering the approved content resulting in a broken site display.

**Comment by SirShaw** [comment]
this appears to be a configuration issue with the end users firewall.
