### ISSUE TITLE
Remote Access to Web API

### ISSUE THREAD

**Issue by Ewwe** [ark-mod/ArkBot#93]
HI, i wanna ask how to authorize from "remote" ? I want to you your product but for my players i have my own website and i want to show them this data. I can access to some methods which have guest in role but cannot resolve auth to api.

On my website im using steam auth so i have steamid availaible. 

Thanks for response

**Comment by SirShaw** [comment]
Please do not use github as a support forum, please see the welcome page for information on how to get support from our discord.
