### ISSUE TITLE
System.IO.FileNotFoundException-WinSrv16- Arkbot not Starting

### ISSUE THREAD

**Issue by kap6254** [ark-mod/ArkBot#95]
Hi, Download the ArkBot Zip Runtime, filled in the config file but ArkBot is not executing.

![grafik](https://user-images.githubusercontent.com/39535846/60301738-6c8b6500-9932-11e9-8275-d7ea3809a74e.png)

![grafik](https://user-images.githubusercontent.com/39535846/60301751-76ad6380-9932-11e9-93dc-affb38503674.png)

![grafik](https://user-images.githubusercontent.com/39535846/60301777-82992580-9932-11e9-8ea1-e36a14eea292.png)

![grafik](https://user-images.githubusercontent.com/39535846/60301796-8b89f700-9932-11e9-9a5e-e13cf56ef009.png)

redistributable is installed, someone has an idea?

thanks :)

**Comment by jefferson-1** [comment]
Please join the discord. https://discord.gg/zDJcckF
