### ISSUE TITLE
Dinos stats level higher than 127 going back to -128

### ISSUE THREAD

**Issue by flagoss** [ark-mod/ArkBot#98]
Dinos stats level higher than 127 going back to -128. 

You just need to change dinos stats from sbyte to byte. I tested that and it worked well. 

Could you please add those change in the next version ?

[https://github.com/flagoss/ArkSavegameToolkitNet/commit/17cff5654e8e228af2e5c4ee381f36c571115671](https://github.com/flagoss/ArkSavegameToolkitNet/commit/17cff5654e8e228af2e5c4ee381f36c571115671)

@jefferson-1

**Comment by mxtsdev** [comment]
https://github.com/ark-mod/ArkBot/pull/125
