### ISSUE TITLE
ArkBot Dont Launch

### ISSUE THREAD

**Issue by islanublark** [ark-mod/ArkBot#99]
I just downloaded ArkBot on a new pc, when trying to launch arkbot.exe, nothing happens.

I think it could be because some program is missing that Is need. I have tried another computer and it goes perfectly.

Thanks for the help.

**Comment by jefferson-1** [comment]
On the main Github site we post how to join Discord to ask for help.

From there react to get the role needed ... follow the directions on joining discord and located in the welcome channels.

**Comment by islanublark** [comment]
thank you, i will follow your instructions.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by doublee313** [comment]
Make sure .net is installed (check in add/remove features). Vcruntimes (all
in one works).
